name: S3 Deploy

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: setup bullshit 1
        run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/

      - name: setup bullshit 2
        run: npm config set "//npm.fontawesome.com/:_authToken" A02743BB-0B14-4D8D-B0F2-0FC5BA43BB9E

      - name: Install dependencies
        run: npm ci

      - name: Database shite
        run: npm run updateDB

      - name: Build
        run: npm run build-only

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: vrc.folf.io
          bucket-region: eu-west-2
          delete-removed: true
          no-cache: true
          private: true
